backend:
field:
label: Tag
name: tag
widget: string
- label: "Texte CTA"
name: cta
widget: string
default: "Voir détails"
- label: Lien
name: href
widget: string
required: false


- label: Formation
name: education
widget: list
fields:
- label: Titre
name: title
widget: string
- label: Sous-titre
name: sub
widget: string
required: false
- label: Points
name: bullets
widget: list
field:
label: Point
name: point
widget: string


- label: Contact
name: contact
widget: object
fields:
- label: Email
name: email
widget: string
- label: LinkedIn
name: linkedin
widget: string
- label: GitHub
name: github
widget: string
